# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=11, unique=True)),
                ('occupation', models.CharField(default='none', max_length=100)),
                ('address', models.CharField(default='none', max_length=100)),
                ('url', models.URLField()),
                ('last_login', models.CharField(max_length=50)),
            ],
        ),
    ]
