# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 13:20
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('hot', models.IntegerField()),
                ('scan', models.IntegerField()),
            ],
        ),
    ]
