# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='hot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='scan',
            field=models.IntegerField(default=0),
        ),
    ]
