# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20170428_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtype',
            name='blog_type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
