# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20170428_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='scan',
        ),
    ]
